// 所有懒加载组件映射
export const lazyComponentsMap = {
  // 3D/视差组件
  LazyLiquidWave: () => import('./components/ScrollLiquidWave.vue'),
  LazyParticleExplosion: () => import('./components/ScrollParticleExplosion.vue'),
  LazyNumberCounter: () => import('./components/ScrollNumberCounter.vue'),
  LazyBouncingBall: () => import('./components/ScrollBouncingBall.vue'),
  LazyCircularProgress: () => import('./components/ScrollCircularProgress.vue'),
  LazyTextReveal: () => import('./components/ScrollTextReveal.vue'),
  LazyMagneticButton: () => import('./components/ScrollMagneticButton.vue'),
  LazyParallaxCards: () => import('./components/ScrollParallaxCards.vue'),
  LazyRotatingRings: () => import('./components/ScrollRotatingRings.vue'),
  LazyTextDistortion: () => import('./components/ScrollTextDistortion.vue'),
  LazyGlassmorphismGallery: () => import('./components/ScrollGlassmorphismGallery.vue'),
  LazyInfiniteScrollText: () => import('./components/ScrollInfiniteScrollText.vue'),
  LazyHolographic3D: () => import('./components/ScrollHolographic3D.vue'),
  LazyNeonGlowText: () => import('./components/ScrollNeonGlowText.vue'),
  LazyMorphingShapes: () => import('./components/ScrollMorphingShapes.vue'),

  // 创意特效
  LazyCyberpunkCity: () => import('./components/ScrollCyberpunkCity.vue'),
  LazyDNAHelix: () => import('./components/ScrollDNAHelix.vue'),
  LazyAuroraBorealis: () => import('./components/ScrollAuroraBorealis.vue'),
  LazyGalaxySpiral: () => import('./components/ScrollGalaxySpiral.vue'),
  LazyOceanWaves: () => import('./components/ScrollOceanWaves.vue'),
  LazyQuantumField: () => import('./components/ScrollQuantumField.vue'),
  LazyVolcanicEruption: () => import('./components/ScrollVolcanicEruption.vue'),
  LazySolarSystem: () => import('./components/ScrollSolarSystem.vue'),
  LazyTornado: () => import('./components/ScrollTornado.vue'),

  // 滚动交互组件
  LazyParallaxZoomGallery: () => import('./components/ScrollParallaxZoomGallery.vue'),
  LazyRotationCarousel: () => import('./components/ScrollRotationCarousel.vue'),
  LazyFadeInStack: () => import('./components/ScrollFadeInStack.vue'),
  LazyScaleWave: () => import('./components/ScrollScaleWave.vue'),
  LazyHorizontalScroll: () => import('./components/ScrollHorizontalScroll.vue'),
  LazyDiagonalParallax: () => import('./components/ScrollDiagonalParallax.vue'),
  LazyRotationGallery: () => import('./components/ScrollRotationGallery.vue'),
  LazyTextScroll: () => import('./components/ScrollTextScroll.vue'),
  LazyScaleShapes: () => import('./components/ScrollScaleShapes.vue'),
  LazyGradientFlow: () => import('./components/ScrollGradientFlow.vue'),
  LazyCascadeParallax: () => import('./components/ScrollCascadeParallax.vue'),
  LazyFloatingImages: () => import('./components/ScrollFloatingImages.vue'),
  LazyStaggerGrid: () => import('./components/ScrollStaggerGrid.vue'),
  LazyStaggerTimeline: () => import('./components/ScrollStaggerTimeline.vue'),
  LazyStaggerCards: () => import('./components/ScrollStaggerCards.vue'),
  LazyCircleGallery: () => import('./components/ScrollCircleGallery.vue'),
  LazyFoldEffect: () => import('./components/ScrollFoldEffect.vue'),
  LazyMorphGrid: () => import('./components/ScrollMorphGrid.vue'),
  LazyWaveReveal: () => import('./components/ScrollWaveReveal.vue'),
  LazyZoomPan: () => import('./components/ZoomPan.vue'),
  LazyRotateScale: () => import('./components/ScrollRotateScale.vue'),
  LazyScrollReveal: () => import('./components/ScrollReveal.vue'),
  LazyParallaxScroll: () => import('./components/ScrollParallaxScroll.vue'),
  LazyFixedParallax: () => import('./components/ScrollFixedParallax.vue'),
  LazyTimelineSequence: () => import('./components/TimelineSequence.vue'),
  LazyOverlappingTimeline: () => import('./components/OverlappingTimeline.vue'),
  LazyNestedTimeline: () => import('./components/NestedTimeline.vue'),
  LazyFlipCards: () => import('./components/ScrollFlipCards.vue'),
  LazySlidingPanels: () => import('./components/SlidingPanels.vue'),
  LazyMorphingCards: () => import('./components/ScrollMorphingCards.vue'),
  LazyMotionPathCards: () => import('./components/ScrollMotionPathCards.vue'),
  LazyCircleMotion: () => import('./components/ScrollCircleMotion.vue'),
  LazyInfinityMotion: () => import('./components/ScrollInfinityMotion.vue'),

  LazyNebulaVortex: () => import('./components/ScrollNebulaVortex.vue'),
  LazyAccordionCards: () => import('./components/ScrollAccordionCards.vue'),
  LazyTabSwitch: () => import('./components/ScrollTabSwitch.vue'),
  LazyImageComparison: () => import('./components/ScrollImageComparison.vue'),
  LazyCardStack: () => import('./components/ScrollCardStack.vue'),
  LazyHorizontalScrollCards: () => import('./components/ScrollHorizontalScrollCards.vue'),
  LazyScrollCard3D: () => import('./components/ScrollCard3D.vue'),
  LazyScrollTextBlur: () => import('./components/ScrollTextBlur.vue'),
  LazyScrollShapeElastic: () => import('./components/ScrollShapeElastic.vue'),

  LazyScrollStaggerWave: () => import('./components/ScrollStaggerWave.vue'),
  LazyScrollParallaxLayer: () => import('./components/ScrollParallaxLayer.vue'),
  LazyScrollMagneticRotate: () => import('./components/ScrollMagneticRotate.vue'),
  LazyScrollFluidPanels: () => import('./components/ScrollFluidPanels.vue'),
  LazyScrollGravityBounce: () => import('./components/ScrollGravityBounce.vue'),
  LazyScrollPixelCard: () => import('./components/ScrollPixelCard.vue'),

  LazyScrollLaserLine: () => import('./components/ScrollLaserLine.vue'),
  LazyScrollHologram: () => import('./components/ScrollHologram.vue'),
  LazyScrollLiquidMorph: () => import('./components/ScrollLiquidMorph.vue'),

  LazyScrollNeonPulse: () => import('./components/ScrollNeonPulse.vue'),
  LazyScrollTimeWarp: () => import('./components/ScrollTimeWarp.vue'),
  LazyScrollCrystalShatter: () => import('./components/ScrollCrystalShatter.vue'),
  LazyQuantumWormhole: () => import('./components/ScrollQuantumWormhole.vue'),
  LazyMagneticOrbit: () => import('./components/ScrollMagneticOrbit.vue'),
  LazySpringBounce: () => import('./components/ScrollSpringBounce.vue'),

  LazyScrollImageReveal: () => import('./components/ScrollImageReveal.vue'),
  LazyScrollTextSplit: () => import('./components/ScrollTextSplit.vue'),
  LazyScrollCardFloat: () => import('./components/ScrollCardFloat.vue'),
  LazyScrollMagnify: () => import('./components/ScrollMagnify.vue'),
  LazyScrollParallaxText: () => import('./components/ScrollParallaxText.vue'),
  LazyScroll3DGallery: () => import('./components/Scroll3DGallery.vue'),

  LazyScrollImageFlow: () => import('./components/ScrollImageFlow.vue'),
  LazyScrollTextCurtain: () => import('./components/ScrollTextCurtain.vue'),
  LazyScrollCardWave: () => import('./components/ScrollCardWave.vue'),

  LazyScrollImageDistort: () => import('./components/ScrollImageDistort.vue'),
  LazyScrollText3D: () => import('./components/ScrollText3D.vue'),
  LazyScrollCardPolaroid: () => import('./components/ScrollCardPolaroid.vue'),

  LazyScrollInkReveal: () => import('./components/ScrollInkReveal.vue'),
  LazyScrollParticleText: () => import('./components/ScrollParticleText.vue'),
  LazyScrollFoldCard: () => import('./components/ScrollFoldCard.vue'),
  LazyScrollMagneticFluid: () => import('./components/ScrollMagneticFluid.vue'),
  LazyScrollGlitchText: () => import('./components/ScrollGlitchText.vue'),

  LazyScrollImageStackReveal: () => import('./components/ScrollImageStackReveal.vue'),
  LazyScrollTextWaveSplit: () => import('./components/ScrollTextWaveSplit.vue'),
  LazyScrollCard3DFlip: () => import('./components/ScrollCard3DFlip.vue'),
  LazyScrollParallaxGallery: () => import('./components/ScrollParallaxGallery.vue'),
  LazyScrollElasticText: () => import('./components/ScrollElasticText.vue'),
  LazyScrollMagneticCards: () => import('./components/ScrollMagneticCards.vue'),
  LazyScrollInfiniteScroll: () => import('./components/ScrollInfiniteScroll.vue'),
  LazyScrollWaveCards: () => import('./components/ScrollWaveCards.vue'),

  LazyScrollLensReveal: () => import('./components/ScrollLensReveal.vue'),
  LazyScrollMorphPath: () => import('./components/ScrollMorphPath.vue'),
  LazyScrollTimeline: () => import('./components/ScrollTimeline.vue'),
  LazyScrollTextScatter: () => import('./components/ScrollTextScatter.vue'),
  LazyScrollCardStack: () => import('./components/ScrollCardStack.vue'),
  LazyScrollGradientFlow: () => import('./components/ScrollGradientFlow.vue'),
  LazyScrollParticleWave: () => import('./components/ScrollParticleWave.vue'),
  LazyScrollImageMosaic: () => import('./components/ScrollImageMosaic.vue'),

  LazyScrollFluidText: () => import('./components/ScrollFluidText.vue'),
  LazyScrollMorphingCards: () => import('./components/ScrollMorphingCards.vue'),
  LazyScrollRippleCards: () => import('./components/ScrollRippleCards.vue'),
  LazyScrollDistortGallery: () => import('./components/ScrollDistortGallery.vue'),
  LazyScrollMagneticGrid: () => import('./components/ScrollMagneticGrid.vue'),
  LazyScrollFoldEffect: () => import('./components/ScrollPaperFold.vue'),
  LazyScroll3DTunnel: () => import('./components/Scroll3DTunnel.vue'),
  LazyScrollSpiralReveal: () => import('./components/ScrollSpiralReveal.vue'),

  LazyScrollGlitchEffect: () => import('./components/ScrollGlitchEffect.vue'),
  LazyScrollAuroraField: () => import('./components/ScrollAuroraField.vue'),
  LazyScrollMagneticOrbitCards: () => import('./components/ScrollMagneticOrbitCards.vue'),
  LazyScrollNeonTrailCards: () => import('./components/ScrollNeonTrailCards.vue'),
  LazyScrollHologramGallery: () => import('./components/ScrollHologramGallery.vue'),
  LazyScrollLiquidDistort: () => import('./components/ScrollLiquidDistort.vue'),
  LazyScrollPrismCards: () => import('./components/ScrollPrismCards.vue'),
  LazyScrollTemporalDistortion: () => import('./components/ScrollTemporalDistortion.vue'),

  LazyScrollCyberGrid: () => import('./components/ScrollCyberGrid.vue'),
  LazyScrollQuantumPortal: () => import('./components/ScrollQuantumPortal.vue'),
  LazyScrollNeonMatrix: () => import('./components/ScrollNeonMatrix.vue'),
  LazyScrollCrystalPrism: () => import('./components/ScrollCrystalPrism.vue'),
  LazyScrollAuroraAurora: () => import('./components/ScrollAuroraAurora.vue'),
  LazyScrollGalaxyVortex: () => import('./components/ScrollGalaxyVortex.vue'),
  LazyScrollInfinityMirrors: () => import('./components/ScrollInfinityMirrors.vue'),
  LazyScrollNeonRain: () => import('./components/ScrollNeonRain.vue'),

  LazyScrollParallaxCardsScroll: () => import('./components/ScrollParallaxCardsScroll.vue'),
  LazyScrollTextCascadEffect: () => import('./components/ScrollTextCascadEffect.vue'),
  LazyScrollCardMorphReveal: () => import('./components/ScrollCardMorphReveal.vue'),
  LazyScrollSplitTransition: () => import('./components/ScrollSplitTransition.vue'),

  LazyScrollParallaxDepth: () => import('./components/ScrollParallaxDepth.vue'),
  LazyScrollMagneticField: () => import('./components/ScrollMagneticField.vue'),
  LazyScrollGeometricFlow: () => import('./components/ScrollGeometricFlow.vue'),

  LazyScrollLiquidCards: () => import('./components/ScrollLiquidCards.vue'),
  LazyScrollNeonGlow: () => import('./components/ScrollNeonGlow.vue'),
  LazyScroll3DCube: () => import('./components/Scroll3DCube.vue'),
  LazyScrollOrbitGallery: () => import('./components/ScrollOrbitGallery.vue'),

  LazyScrollHologramCards: () => import('./components/ScrollHologramCards.vue'),

  LazyScrollMorphGallery: () => import('./components/ScrollMorphGallery.vue'),

  LazyScrollLiquidText: () => import('./components/ScrollLiquidText.vue'),
  LazyScrollQuantumCards: () => import('./components/ScrollQuantumCards.vue'),
  LazyScrollAuroraText: () => import('./components/ScrollAuroraText.vue'),
  LazyScrollVortexCards: () => import('./components/ScrollVortexCards.vue'),

  LazyScrollPixelCards: () => import('./components/ScrollPixelCards.vue'),
  LazyScrollRibbonCards: () => import('./components/ScrollRibbonCards.vue'),
  LazyScrollOrigamiCards: () => import('./components/ScrollOrigamiCards.vue'),
  LazyScrollGlassMorph: () => import('./components/ScrollGlassMorph.vue'),

  LazyScrollEmberCards: () => import('./components/ScrollEmberCards.vue'),
  LazyScrollPlasmaWaves: () => import('./components/ScrollPlasmaWaves.vue'),
  LazyScrollHoloCards: () => import('./components/ScrollHoloCards.vue'),
  LazyScrollLiquidMetal: () => import('./components/ScrollLiquidMetal.vue'),
  LazyScrollVortexRing: () => import('./components/ScrollVortexRing.vue'),
  LazyScrollPrismGlow: () => import('./components/ScrollPrismGlow.vue'),
  LazyScrollElectricArc: () => import('./components/ScrollElectricArc.vue'),
  LazyScrollNeonGrid: () => import('./components/ScrollNeonGrid.vue'),
  LazyScrollIceCrystal: () => import('./components/ScrollIceCrystal.vue'),
  LazyScrollSolarFlare: () => import('./components/ScrollSolarFlare.vue'),
  LazyScrollAuroraNight: () => import('./components/ScrollAuroraNight.vue'),
  LazyScrollCosmicDust: () => import('./components/ScrollCosmicDust.vue'),
  LazyScrollFrostBreath: () => import('./components/ScrollFrostBreath.vue'),
  LazyScrollLavaFlow: () => import('./components/ScrollLavaFlow.vue'),

  LazyScrollMorphingText: () => import('./components/ScrollMorphingText.vue'),
  LazyScrollEnergyOrb: () => import('./components/ScrollEnergyOrb.vue'),
  LazyScrollQuantumLeap: () => import('./components/ScrollQuantumLeap.vue'),
  LazyScrollCyberPulse: () => import('./components/ScrollCyberPulse.vue'),
  LazyScrollStardustReveal: () => import('./components/ScrollStardustReveal.vue'),
  LazyScrollTemporalFlux: () => import('./components/ScrollTemporalFlux.vue'),
  LazyScrollQuantumTextEntangle: () => import('./components/ScrollQuantumTextEntangle.vue'),
  LazyScrollShadowText: () => import('./components/ScrollShadowText.vue'),
  LazyScrollLiquidTextMorph: () => import('./components/ScrollLiquidTextMorph.vue'),
  LazyScrollPixelTextReveal: () => import('./components/ScrollPixelTextReveal.vue'),
  LazyScrollHolographicText: () => import('./components/ScrollHolographicText.vue'),
  LazyScrollPortalText: () => import('./components/ScrollPortalText.vue'),
  LazyScrollPrismText: () => import('./components/ScrollPrismText.vue'),
  LazyScrollNeonText: () => import('./components/ScrollNeonText.vue'),
  LazyScrollCyberText: () => import('./components/ScrollCyberText.vue'),
  LazyScrollMatrixText: () => import('./components/ScrollMatrixText.vue'),
  LazyScrollHoloText: () => import('./components/ScrollHoloText.vue'),
  LazyScrollFireText: () => import('./components/ScrollFireText.vue'),
  LazyScrollIceText: () => import('./components/ScrollIceText.vue'),

  LazyScrollCursorFollower: () => import('./components/ScrollCursorFollower.vue'),
  LazyScrollMagnetic: () => import('./components/ScrollMagnetic.vue'),
  LazyScrollStickyReveal: () => import('./components/ScrollStickyReveal.vue'),
  LazyScrollParallaxCursor: () => import('./components/ScrollParallaxCursor.vue'),
  LazyScrollScaleOnScroll: () => import('./components/ScrollScaleOnScroll.vue'),
  LazyScrollGlitch: () => import('./components/ScrollGlitch.vue'),
  LazyScrollInvert: () => import('./components/ScrollInvert.vue'),
  LazyScrollContrast: () => import('./components/ScrollContrast.vue'),
  LazyScrollHoverReveal: () => import('./components/ScrollHoverReveal.vue'),
  LazyScrollDragReveal: () => import('./components/ScrollDragReveal.vue'),
  LazyScrollPinchZoom: () => import('./components/ScrollPinchZoom.vue'),
  LazyScrollSwipeUp: () => import('./components/ScrollSwipeUp.vue'),
  LazyScrollThemeSwitch: () => import('./components/ScrollThemeSwitch.vue'),
  LazyScrollAccentColor: () => import('./components/ScrollAccentColor.vue'),
  LazyScrollElasticMorph: () => import('./components/ScrollElasticMorph.vue'),
  LazyScrollInkDiffusion: () => import('./components/ScrollInkDiffusion.vue'),
  LazyScrollLiquidButtons: () => import('./components/ScrollLiquidButtons.vue'),

  LazyScrollPaperFold: () => import('./components/ScrollPaperFold.vue'),
  LazyScrollDynamicShadow: () => import('./components/ScrollDynamicShadow.vue'),
  LazyScrollTextWaveMorph: () => import('./components/ScrollTextWaveMorph.vue'),
  LazyScrollSvgPathDraw: () => import('./components/ScrollSvgPathDraw.vue'),
  LazyScrollBlendModeMix: () => import('./components/ScrollBlendModeMix.vue'),
  LazyScrollGridMorph: () => import('./components/ScrollGridMorph.vue'),
  LazyScrollPhysicsBounce: () => import('./components/ScrollPhysicsBounce.vue'),
  LazyScrollBackgroundPattern: () => import('./components/ScrollBackgroundPattern.vue'),
  LazyScrollStorytelling: () => import('./components/ScrollStorytelling.vue'),
  LazyScrollLoadingArt: () => import('./components/ScrollLoadingArt.vue'),

  LazyScrollSplitReveal: () => import('./components/ScrollSplitReveal.vue'),
  LazyScrollTextScramble: () => import('./components/ScrollTextScramble.vue'),
  LazyScrollWavyText: () => import('./components/ScrollWavyText.vue'),
  LazyScrollTextShadow: () => import('./components/ScrollTextShadow.vue'),
  LazyScrollGradientText: () => import('./components/ScrollGradientText.vue'),
  LazyScrollOutlineText: () => import('./components/ScrollOutlineText.vue'),
  LazyScrollTextMask: () => import('./components/ScrollTextMask.vue'),
  LazyScrollTextGlow: () => import('./components/ScrollTextGlow.vue'),
  LazyScrollThunderText: () => import('./components/ScrollThunderText.vue'),
  LazyScrollStarText: () => import('./components/ScrollStarText.vue'),
  LazyScrollRainText: () => import('./components/ScrollRainText.vue'),

  LazyScrollCardZoom: () => import('./components/ScrollCardZoom.vue'),
  LazyScrollCardRotate3D: () => import('./components/ScrollCardRotate3D.vue'),
  LazyScrollCardBorder: () => import('./components/ScrollCardBorder.vue'),
  LazyScrollCardMorph: () => import('./components/ScrollCardMorph.vue'),
  LazyScrollCardGlass: () => import('./components/ScrollCardGlass.vue'),
  LazyScrollCardRipple: () => import('./components/ScrollCardRipple.vue'),
  LazyScrollShapeShift: () => import('./components/ScrollShapeShift.vue'),
  LazyScrollElasticScale: () => import('./components/ScrollElasticScale.vue'),
  LazyScrollPerspective: () => import('./components/ScrollPerspective.vue'),

  LazyScrollParallaxLayers: () => import('./components/ScrollParallaxLayers.vue'),
  LazyScrollImageClip: () => import('./components/ScrollImageClip.vue'),
  LazyScrollImageBlur: () => import('./components/ScrollImageBlur.vue'),
  LazyScrollImageSepia: () => import('./components/ScrollImageSepia.vue'),
  LazyScrollImageTilt: () => import('./components/ScrollImageTilt.vue'),
  LazyScrollImageCircle: () => import('./components/ScrollImageCircle.vue'),
  LazyScrollImageGallerySwipe: () => import('./components/ScrollImageGallerySwipe.vue'),
  LazyScrollImageMasonry: () => import('./components/ScrollImageMasonry.vue'),
  LazyScrollImagePanorama: () => import('./components/ScrollImagePanorama.vue'),
  LazyScrollImageParallaxZoom: () => import('./components/ScrollImageParallaxZoom.vue'),
  LazyScrollImageStack3D: () => import('./components/ScrollImageStack3D.vue'),
  LazyScrollImageWave: () => import('./components/ScrollImageWave.vue'),
  LazyScrollImageZoomReveal: () => import('./components/ScrollImageZoomReveal.vue'),

  LazyScrollTextFlow: () => import('./components/ScrollTextFlow.vue'),
  LazyScrollTextColumns: () => import('./components/ScrollTextColumns.vue'),
  LazyScrollTextJustify: () => import('./components/ScrollTextJustify.vue'),

  LazyScrollNavMorph: () => import('./components/ScrollNavMorph.vue'),
  LazyScrollBreadcrumb: () => import('./components/ScrollBreadcrumb.vue'),
  LazyScrollTabSwitch: () => import('./components/ScrollTabSwitch.vue'),
  LazyScrollFloatingNav: () => import('./components/ScrollFloatingNav.vue'),

  LazyScrollRibbonCards: () => import('./components/ScrollRibbonCards.vue'),
  LazyScrollHueRotate: () => import('./components/ScrollHueRotate.vue'),
}

// 组件名称列表（用于虚拟滚动）
export const lazyComponentNames = Object.keys(lazyComponentsMap)
